name: MetaLambda
version: 0.2
synopsis: Contextual Modal Type Theory
description: Implementation of Contextual Modal Type Theory[Nanevski et al. 2008]
category: LambdaCalculus
github: damhiya/MetaLambda
author: damhiya
maintainer: damhiya@gmail.com
copyright: (c) 2022 SoonWon Moon
license: BSD-3-Clause
license-file: LICENSE
extra-source-files: CHANGELOG.md

# common settings
ghc-options: -Wall -Wno-unused-matches
language: GHC2021
default-extensions:
  - OverloadedStrings
  - LambdaCase
dependencies:
  - base ^>= 4.18
  - text ^>= 2.0

# per-entry settings
internal-libraries:
  Util:
    source-dirs: util
    dependencies:
      - mtl ^>= 2.3

  MetaLambdaLib:
    source-dirs: src
    dependencies:
      - Util
      - containers ^>= 0.6
      - mtl ^>= 2.3
      - megaparsec ^>= 9.6
      - Earley ^>= 0.13
      - prettyprinter ^>= 1.7
    
executables:
  MetaLambda:
    source-dirs: app
    main: Main.hs
    dependencies:
      - Util
      - MetaLambdaLib
      - mtl ^>= 2.3
      - megaparsec ^>= 9.6
      - haskeline ^>= 0.8

tests:
  MetaLambdaTest:
    source-dirs: test
    main: Test.hs
    dependencies:
      - MetaLambdaLib
      - directory ^>= 1.3
      - tasty ^>= 1.5
      - tasty-golden ^>= 2.3
