name: MetaLambda
version: 0.1.0.0
synopsis: Contextual Modal Type Theory
description: Implementation of Contextual Modal Type Theory[Nanevski et al. 2008]
category: LambdaCalculus
github: damhiya/MetaLambda
author: damhiya
maintainer: damhiya@gmail.com
copyright: (c) 2022 SoonWon Moon
license: BSD-3-Clause
license-file: LICENSE
extra-source-files: CHANGELOG.md

# common settings
ghc-options: -Wall -Wno-unused-matches
language: GHC2021
default-extensions:
  - OverloadedStrings
  - LambdaCase
dependencies:
  - base >=4.14 && <5.0
  - text == 2.0

# per-entry settings
internal-libraries:
  Util:
    source-dirs: util
    dependencies:
      - containers
      - mtl

  MetaLambdaLib:
    source-dirs: src
    dependencies:
      - Util
      - containers
      - mtl
      - megaparsec
      - Earley
      - prettyprinter
    
executables:
  MetaLambda:
    source-dirs: app
    main: Main.hs
    dependencies:
      - Util
      - MetaLambdaLib
      - mtl
      - megaparsec
      - haskeline

tests:
  MetaLambdaTest:
    source-dirs: test
    main: Test.hs
    dependencies:
      - MetaLambdaLib
      - directory
      - tasty
      - tasty-golden
